---
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - db/*schema.rb
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 3.4
