---
plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - db/*schema.rb
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 3.4

Layout/LineLength:
  Max: 120

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always