---
extends: default

ignore:
  - .gem_rbs_collection
  - node_modules
  - rbs_collection.lock.yaml

rules:
  comments:
    level: error
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start:
    level: error
  line-length: disable
  truthy: disable
