---
name: Ruby Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup ruby
        uses: ruby/setup-ruby@829114fc20da43a41d27359103ec7a63020954d4 # v1.255.0
        with:
          bundler-cache: true

      - name: Run rubocop
        run: |
          bin/rubocop -f github --parallel

      - name: Run erb_lint
        run: |
          bin/erb_lint --lint-all

      - name: Run brakeman
        run: |
          bin/brakeman --no-pager
