---
name: yamllint

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install yamllint
        run: |
          sudo apt-get install yamllint
          yamllint --version

      - name: Lint YAML files
        run: yamllint .
